spring:
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://user-service:8001
          predicates:
            - Path=/api/users/**
        - id: expense-service-route
          uri: http://expense-service:8000
          predicates:
            - Path=/api/expense/**
      default-filters:
        - name: AuthenticationFilter
          args:
            config:
