version: '3'

services:
  expense-service:
    image: expense-service-image
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/expense_tracker
      SERVER_PORT: 8000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
